#!/bin/bash

if [ -n $1 ]; then
  filename=$1-$(append-date)
  curl -X POST -v -H "$(headers)" https://owner-api.teslamotors.com/api/1/vehicles/$(vehicle-id)/command/$1 > $(tesla-working-directory)/logs/$filename
  cat $(tesla-working-directory)/logs/$filename | python -m json.tool
else
  echo "Please provide a valid command"
fi
