#!/bin/bash

if [ -n $1 ]; then

  currentDirectory=$(dirname $BASH_SOURCE[0])
  filename=$1-$($currentDirectory/utils/append-date)

  curl -X POST -v -H "$($currentDirectory/utils/headers)" https://owner-api.teslamotors.com/api/1/vehicles/$($currentDirectory/config/vehicle-id)/command/$1 > $currentDirectory/logs/$filename
  cat $currentDirectory/logs/$filename | python -m json.tool
  
else
  echo "Please provide a command"
fi
