#!/bin/bash

currentDirectory=$(dirname $BASH_SOURCE[0])
logFileName=data-dump-$($currentDirectory/utils/append-date)

curl -H "$($currentDirectory/utils/headers)" https://owner-api.teslamotors.com/api/1/vehicles/$($currentDirectory/config/vehicle-id)/vehicle_data > $currentDirectory/logs/$logFileName
cat $currentDirectory/logs/$logFileName | python -m json.tool
