#!/bin/bash

if [ -n $1 ]; then

  currentDirectory=$(dirname $BASH_SOURCE[0])
  filename=$1-$($currentDirectory/utils/append-date)

  curl -v -H "$($currentDirectory/utils/headers)" https://owner-api.teslamotors.com/api/1/vehicles/$($currentDirectory/config/vehicle-id)/data_request/$1 > $currentDirectory/logs/$filename
  cat $currentDirectory/logs/$filename | python -m json.tool
  
else
  echo "Please provide data request param"
fi
