#!/bin/bash
filename=wake_up-$(append-date)
curl -X POST -v -H "$(headers)" https://owner-api.teslamotors.com/api/1/vehicles/$(vehicle-id)/wake_up > ~/zscripts/tesla/logs/$filename
cat $(tesla-working-directory)/logs/$filename | python -m json.tool
