#!/bin/bash

currentDirectory=$(dirname $BASH_SOURCE[0])

echo -e "Authorization: Bearer $($currentDirectory/../config/auth-token)\nUser-Agent: curl TeslaAPIWrapper/1.0\nAccept: application/json\nContent-Type: application/json"
